tap "d12frosted/emacs-plus"

brew "asdf"
brew "bat"
brew "chezmoi"
brew "eza"
brew "fzf"
brew "gh"
brew "lolcat"
brew "navi"
brew "neovim"
brew "starship"
brew "tealdeer"
brew "zoxide"
brew "d12frosted/emacs-plus/emacs-plus@30"

cask "claude"
cask "ghostty"
cask "git-credential-manager"
cask "maccy"
cask "rectangle"
cask "zed"
